name: ${project.name}
main: ${project.groupId}.${project.name}
version: ${project.version}
authors: [E_NeLsOn]
api-version: "1.21"
softdepend: [PlaceholderAPI, BreweryX, Brewery]
commands:
  sopmeals:
    description: SopMeals administration
    usage: /sopmeals reload
    aliases: [meals]
permissions:
  sopmeals.admin:
    description: Access to SopMeals admin commands
    default: op
